# Generated by Django 5.1.1 on 2024-09-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='todo',
        ),
    ]
